server:
  port: 9002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/

spring:
  boot:
    admin:
      context-path: /admin