spring:
  application:
    name: coupon

server:
  port: 2004

management:
  endpoints:
    web:
      exposure:
        include: '*'


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/